blog/urls.py
from django.urls import path

from .views import ArticleDetailView, ArticleListView, CategoryListView

app_name = "blog"
urlpatterns = [
    path("", ArticleListView.as_view(), name="list"),
    path("category/", CategoryListView.as_view(), name="category"),
    path("article/<int:id>/", ArticleListView.as_view(), name="detail"),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("airlines/", include("airlines.urls", namespace="airlines")),
    path("", include("passangers.urls", namespace="passengers")),
    path("hotels/", include("hotels.urls", namespace="hotel")),
    path("core/", include("core.urls", namespace="core")),
    path("job/", include("jobs.urls", namespace="job")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("pro/", include("profiles.urls", namespace="user_pro")),
    # path('api_doc/',include_docs_urls(title='7BLUSKY')),

]

if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

passangers/urls.py
from django.urls import path

from .views import (CancelTicketView, PassengerView, TripInfoView, cities,
                    go_to_gateway_view, home)

app_name = "passengers"
urlpatterns = [
    path("", home, name="home"),
    path(
        "cancel/ticket/<int:reserve_id>/",
        CancelTicketView.as_view(),
        name="cancel_reserve",
    ),
    path("trip/", TripInfoView.as_view(), name="trip"),
    # path("", go_to_gateway_view, name="pay"),
    path("toBank/", go_to_gateway_view, name="pay"),
    path("cities/", cities, name="cities"),
    path("passenger/", PassengerView.as_view(), name="passenger"),
]

passangers/models.py
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django_extensions.db.models import TimeStampedModel

from airlines.models import Airline

user = settings.AUTH_USER_MODEL


# Create your models here.


class Reservation(models.Model):
    user = models.ForeignKey(
        user, on_delete=models.CASCADE, related_name="reservation", verbose_name="کاربر"
    )
    air_line = models.ForeignKey(
        Airline,
        on_delete=models.CASCADE,
        related_name="air_line_reservation",
        blank=True,
        null=True,
    )
    fly_code = models.CharField(max_length=125, verbose_name="کد پرواز")
    flight_class = models.CharField(max_length=125, blank=True)
    flight_no = models.CharField(max_length=125, blank=True)
    source = models.CharField(max_length=125, verbose_name="مبذا")
    target = models.CharField(max_length=125, verbose_name="مقصد")
    # price = models.IntegerField(verbose_name='')
    date = models.CharField(max_length=125, verbose_name="تاریخ")
    email = models.EmailField()
    phone_number = models.CharField(max_length=125, verbose_name="شماره تماس")
    paid = models.BooleanField(default=False, verbose_name="پرداخت شده؟")
    pnr_code = models.CharField(max_length=125, blank=True, verbose_name="شناسه رزرو")

    def __str__(self):
        return f"{self.user}  رزروهای "

    def get_total_cost(self):
        return self.passengers.aggregate(Sum("price"))["price__sum"]

    class Meta:
        verbose_name = "رزرو"
        verbose_name_plural = "رزروها"


class Passenger(models.Model):
    GENDER = (
        ("مرد", "مرد"),
        ("زن", "زن"),
    )
    en_name = models.CharField(
        max_length=125,
    )
    en_family = models.CharField(max_length=125, verbose_name="نام لایتن")
    gender = models.CharField(max_length=12, choices=GENDER, verbose_name="جنسیت")
    national_code = models.CharField(max_length=10, verbose_name="کد ملی")
    ir_name = models.CharField(max_length=125, verbose_name="نام")
    ir_family = models.CharField(max_length=125, verbose_name="نام خانوادگی")
    date=models.CharField(max_length=125)
    reserve = models.ForeignKey(
        Reservation,
        on_delete=models.CASCADE,
        related_name="passengers",
        verbose_name="رزرو کننده",
    )
    price = models.IntegerField(verbose_name="قیمت")
    age = models.CharField(max_length=125, verbose_name="سن")

    def __str__(self):
        return f"{self.ir_name} {self.ir_family}"

    def en_full_name(self):
        return f"{self.en_name} {self.en_family}"

    class Meta:
        verbose_name = "مسافر"
        verbose_name_plural = "مسافر ها"

passangers/views.py
import datetime
import json
import logging

import requests
# from azbankgateways import bankfactories
# from azbankgateways import default_settings as settings
# from azbankgateways import models as bank_models
# from azbankgateways.exceptions import AZBankGatewaysException
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
#
#
# # Create your views here.
#
#
# class ReserveCreateView(View):
#     form_class = PassengerForm
#     template_name = "passengers/reserve.html"
#
#     def get(self, request):
#         return render(request, self.template_name, {"form": self.form_class})
#
#     def post(self, request):
#         form = self.form_class(request.POST)
#         if form.is_valid():
#             cd = form.save(commit=False)
#             cd.reserver = request.user
#             cd.fly_code = request.POST.get("fly_code")
#             cd.save()
#             messages.success(request, "", "success")
#             return redirect()
#         else:
#             messages.error(request, "", "danger")
#         return render(request, self.template_name, {"form": form})
from django.views import View

from airlines.models import Airline
from passangers.models import Passenger

from .models import Passenger, Reservation

# from django.views.generic import View
#





def home(request):
    return render(request, "index.html")


class PassengerView(View):
    template_name = "passengers/passengers.html"

    def get(self, request):
        info = {
            "airline_name": request.GET.get("airline_name"),
            "DepartureTime": request.GET.get("DepartureTime"),
            "ArrivalTime": request.GET.get("ArrivalTime"),
            "Destination": request.GET.get("Destination"),
            "date": request.GET.get("persian_date"),
            "origin": request.GET.get("origin_city_name"),
            "destination": request.GET.get("destination_city_name"),
            "logo": request.GET.get("trip_image"),
            'fly_code': request.GET.get('fly_code_number',None),
            'fly_class': request.GET.get('fly_class_code')
        }
        context = {}

        try:
            # context['passenger_info'] = request.session['passenger_info']
            passenger_number = request.session["passenger_info"]
            context["passenger_info"] = passenger_number

        except:
            context["passenger_info"] = {}
        airline = Airline.objects.get(name=info.get("airline_name"))
        # price = requests.get(
        #     f'{airline.base_url}/FareJS.jsp?AirLine={airline.symbol}&Route={request.GET.get("Origin")}-{request.GET.get("Destination")}&RBD={request.GET.get("fly_code")}&DepartureDate={request.GET.get("persian_date")}&FlightNo={request.GET.get("flight_no")}&OfficeUser={airline.username}&OfficePass={airline.password}')
        # price_list = json.loads(price.content.decode('ISO-8859-1'))
        # prices = {'adult': price_list["AdultTotalPrice"], 'child': price_list["ChildTotalPrice"],
        #           'infant': price_list["InfantTotalPrice"]}
        context['price_list']: prices
        context["air_line"] = airline
        context["info"] = info
        return render(request, self.template_name, context)

    def post(self, request):
        # email = request.user.profile.email
        phone_number = request.user.phone_number
        airline = Airline.objects.first()
        if request.POST.get("email"):
            email = request.POST.get("email")
            phone_number = request.POST.get("phone_number")

        reserve = Reservation.objects.create(
            user_id=request.user.id,
            air_line=airline,
            fly_code=request.POST.get("fly_code"),
            flight_class=request.POST.get('fly_class'),
            source=request.POST.get("source"),
            target=request.POST.get("target"),
            date=request.POST.get("date"),
            email="elel@fmal.com",
            phone_number=phone_number,
            paid=False,
        )
        passengers = []
        for key, value in dict(request.POST).items():
            for i in range(0, len(value)):
                if len(passengers) > i:
                    passenger = passengers[i]
                else:
                    passenger = Passenger()
                    passenger.price = 0
                    passenger.reserve = reserve
                if key == "latinName":
                    passenger.en_name = value[i]
                elif key == "date":
                    passenger.date = value[i]
                elif key == "latinFamilyName":
                    passenger.en_family = value[i]
                elif key == "gender":
                    passenger.gender = value[i]
                elif key == "nationalCode":
                    passenger.national_code = value[i]
                elif key == "name":
                    passenger.ir_name = value[i]
                elif key == "familyName":
                    passenger.ir_family = value[i]
                if len(passengers) > i:
                    passengers[i] = passenger
                else:
                    passengers.append(passenger)

        Passenger.objects.bulk_create(passengers)
        return redirect("passengers:trip")


class TripInfoView(View):
    def get(self, request):
        reserve_obj = Reservation.objects.last()
        return render(request, "passengers/infoSubmit.html", {"reserve": reserve_obj})


class CancelTicketView(View):
    def get(self, request, reserve_id):
        reserve_obj = get_object_or_404(Reservation, id=reserve_id)
        reserve_obj.delete()
        return redirect("passengers:home")


class Reserve(View):
    def get(self, request):
        reserve_obj = Reservation.objects.first()
        # for i in reserve_obj.
        requests.get(
            f"{reserve_obj.air_line.base_url}/ReservJS?AirLine={reserve_obj.air_line.symbol}&cbSource={reserve_obj.source}&cbTarget={reserve_obj.target}Q&FlightClass={reserve_obj.flight_class}&FlightNo={reserve_obj.flight_no}&Day&Month&No=1&edtName1={reserve_obj.first_name}&edtLast1={reserve_obj.last_name}&edtAge1={reserve_obj.age}&edtID1={reserve_obj.national_code}&edtContact={reserve_obj.phone_number}&DepartureDate=2022-03-03&OfficeUser={reserve_obj.air_line.username}&OfficePass{reserve_obj.air_line.password}"
        )


def go_to_gateway_view(request):
    pass
    amount = 1000
    user_mobile_number = "+989112221234"
    info = {
        "ResNum": "111111",
        "amount": amount,
        "cell": user_mobile_number,
    }
    return render(request, "passengers/payTest.html", {"info": info})
    # factory = bankfactories.BankFactory()
    # try:
    #     bank = factory.auto_create()
    #     bank.set_request(request)
    #     bank.set_amount(amount)
    #     bank.set_client_callback_url(reverse("callback-gateway"))
    #     bank.set_mobile_number(user_mobile_number)  # اختیاری
    #
    #     bank_record = bank.ready()
    #
    #     return bank.redirect_gateway()
    # except AZBankGatewaysException as e:
    #     logging.critical(e)
    #     # TODO: redirect to failed page.
    #     raise e


def cities(request):
    # re = requests.get('https://api.vhotel.ir/api/V4/cities', auth=('admin', "iEol5iBJjFCRKIBA"))
    # data = re.text
    data = {
        "ABD": "آبادان",
        "AKW": "آقاجاری",
        "AEU": "ابوموسی",
        "AJK": "اراک",
        "ADU": "اردبیل",
        "OMH": "ارومیه",
        "IFN": "اصفهان",
        "OMI": "امیدیه",
        "AWZ": "اهواز",
        "IHR": "ایران شهر",
        "IIL": "ایلام",
        "BBL": "بابلسر",
        "BJB": "بجنورد",
        "BXR": "بم",
        "BND": "بندر عباس",
        "BDH": "بندر لنگه",
        "MRX": "بندر ماهشهر",
        "IAQ": "بهرگان",
        "BUZ": "بوشهر",
        "XBJ": "بیرجند",
        "BSM": "بیشه کلا",
        "PFQ": "پارس آباد",
        "TBZ": "تبریز",
        "TCX": "طبس",
        "IKA": "تهران(امام خمینی)",
        "THR": "تهران",
        "TEW": "توحید",
        "KHK": "جزیره خارک",
        "SXI": "جزیره سیری",
        "KIH": "جزیره کیش",
        "JYR": "جیرفت",
        "ZBR": "چابهار",
        "KHA": "خانه",
        "KHD": "خرم آباد",
        "KHY": "خوی",
        "DEF": "دزفول",
        "RZR": "رامسر",
        "RAS": "رشت",
        "RJN": "رفسنجان",
        "ACZ": "زابل",
        "ZAH": "زاهدان",
        "JWN": "زنجان",
        "SRY": "ساری",
        "AFZ": "سبزوار",
        "CKT": "سرخس",
        "SDG": "سنندج",
        "ACP": "سهند",
        "SYJ": "سیرجان",
        "CQD": "شهر کرد",
        "SYZ": "شیراز",
        "PGU": "عسلویه",
        "FAZ": "فاسا",
        "GZW": "قزوین",
        "GSM": "قشم",
        "GCH": "گچساران",
        "GBT": "گورگن",
        "LRR": "لار",
        "LFM": "لامرد",
        "LVP": "لاوان",
        "MHD": "مشهد",
        "NUJ": "نوژه",
        "NSH": "نوشهر",
        "IFH": "هسا",
        "HDM": "همدان",
        "HDR": "هوادریا",
        "KNR": "کانگان",
        "KER": "کرمان",
        "KSH": "کرمانشاه",
        "KLM": "کلاله",
        "YES": "یاسوج",
        "AZD": "یزد",
    }

    # serialize data obj as a JSON stream
    data = json.dumps(data)
    response = HttpResponse(data, content_type="application/json charset=utf-8")

    return response

passangers/templates/passengers/infoSubmit.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/infosubmit.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <title>خرید بلیط</title>
{% endblock style %}

{% block content %}

    <main class="d-flex py-3 flex-column justify-content-start align-items-start">
        <section class="col-12">
            <div style="height: 70px; background-color: lightgray;" class="progressContainer mb-4">
                <div class="progressBar">
                    <div class="percent"></div>
                </div>
                <div class="steps">
                    <div class="step step1 finished" id="0"></div>
                    <div class="step step2 finished" id="1"></div>
                    <div class="step step3 completed" id="2"></div>
                    <div class="step step4" id="3"></div>
                    <div class="step step5" id="4"></div>
                </div>
            </div>
        </section>


        <section class="information mb-3 p-5 col-12">
            <div class="d-flex mb-3 align-items-start">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                     class="bi bi-ticket-perforated-fill" viewBox="0 0 16 16">
                    <path d="M0 4.5A1.5 1.5 0 0 1 1.5 3h13A1.5 1.5 0 0 1 16 4.5V6a.5.5 0 0 1-.5.5 1.5 1.5 0 0 0 0 3 .5.5 0 0 1 .5.5v1.5a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 11.5V10a.5.5 0 0 1 .5-.5 1.5 1.5 0 1 0 0-3A.5.5 0 0 1 0 6V4.5Zm4-1v1h1v-1H4Zm1 3v-1H4v1h1Zm7 0v-1h-1v1h1Zm-1-2h1v-1h-1v1Zm-6 3H4v1h1v-1Zm7 1v-1h-1v1h1Zm-7 1H4v1h1v-1Zm7 1v-1h-1v1h1Zm-8 1v1h1v-1H4Zm7 1h1v-1h-1v1Z"/>
                </svg>
                <h4 class="ms-2 mt-1 fw-bold">اطلاعات بلیط</h4>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <th>مبدا</th>
                        <td>{{ reserve.source }}</td>
                    </tr>
                    <tr>
                        <th>مقصد</th>
                        <td>{{ reserve.target }}</td>
                    </tr>
                    <tr>
                        <th>شرکت هواپیمایی</th>
                        <td>{{ reserve.air_line }}</td>
                    </tr>
                    <tr>
                        <th>تاریخ و ساعت پرواز</th>
                        <td>{{ reserve.date }}</td>
                    </tr>
                    <tr>
                        <th>شماره پرواز</th>
                        <td>{{ reserve.fly_code }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </section>

        <section class="information mb-3 p-5 col-12">
            <div class="d-flex justify-content-between align-items-center w-100 mb-3">
                <div>
                    <div class="d-flex align-items-start">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                             class="bi bi-people-fill" viewBox="0 0 16 16">
                            <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                            <path fill-rule="evenodd"
                                  d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
                            <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
                        </svg>
                        <h4 class="ms-2 mt-1 fw-bold">مشخصات مسافران</h4>
                    </div>
                </div>
                <div>
                    <a href="passengers.html" class="btn btn-outline-primary">ویرایش مسافران</a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr class="details-header">
                        <th>بازه سنی</th>
                        <th>نام و نام خانوادگی</th>
                        <th>جنسیت</th>
                        <th>کد ملی / شماره پاسپورت</th>
                        <th>تاریخ تولد</th>
                        <th>ملیت</th>
                        <th>قیمت</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for passenger in reserve.passengers.all %}
                        <tr class="details-body">
                            <td>{{ passenger.age }}</td>
                            <td class="d-flex flex-column align-items-center justify-content-center">
                                <div>
                                    {{ passenger }}
                                </div>
                                <small class="text-secondary">
                                    {{ passenger.en_full_name }}
                                </small>
                            </td>
                            <td>{{ passenger.gender }}</td>
                            <td>{{ passenger.national_code }}</td>
                            <td>{{ passenger.birthday }}</td>
                            <td>{{ passenger.nationality }}</td>
                            <td>{{ passenger.price }}<small>ريال</small></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </section>

        <section class="fly-notices mb-3 p-5 col-12">
            <div class="d-flex justify-content-between align-items-center w-100 mb-3">
                <div>
                    <div class="d-flex align-items-start">
                        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                             class="bi bi-envelope-fill" viewBox="0 0 16 16">
                            <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z"/>
                        </svg>
                        <h4 class="ms-2 mt-1 fw-bold">اطلاع رسانی سفر</h4>
                    </div>
                </div>
            </div>
            <div class="d-flex align-items-start">
                <svg xmlns="http://www.w3.org/2000/svg" style="color: #A85D00;" width="20" height="20"
                     fill="currentColor" class="bi bi-exclamation-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"/>
                </svg>
                <div style="color: #A85D00;" class="ms-2">
                    اطلاعات بلیط و اطلاع‌رسانی بعدی به این آدرس ارسال می‌شود.
                </div>
            </div>
            <div class="d-flex email-phone justify-content-start align-items-center mt-3">
                <div class="d-flex align-items-start me-3">
                    <h5 class="fw-bold">ایمیل: </h5>
                    <div class="ms-2 text-secondary">{{ reserve.email }}</div>
                </div>
                <div class="d-flex align-items-start ms-3">
                    <h5 class="fw-bold">شماره موبایل: </h5>
                    <div class="ms-2 text-secondary">{{ reserve.phone_number }}</div>
                </div>
            </div>
        </section>

        <section class="payment mb-3 col-12 p-4 d-flex justify-content-between align-items-center">
            <div class="text-primary me-2 d-flex align-items-center">
                <h6 class="me-4 text-body">مبلغ قابل پرداخت</h6>
                <h4 class="fw-bold">
                    {{ reserve.get_total_cost }}
                </h4>
                <small class="ms-1">ریال</small>
            </div>
            <div class="btn-accept-cancel">
                <a href="{% url "passengers:cancel_reserve" reserve.id %}"
                   class="btn ms-2 px-5 fw-bold btn-outline-dark">انصراف</a>
                <a href="{% url "passengers:pay" %}"
                   class="btn ms-2 px-5 fw-bold btn-primary">پرداخت</a>
            </div>
        </section>

        <div class="modal fade" id="paymentModal" tabindex="-1" aria-labelledby="paymentModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body p-5">
                        <div class="d-flex justify-content-center align-items-start">
                            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                                 class="bi bi-check2-square me-2 text-success" viewBox="0 0 16 16">
                                <path d="M3 14.5A1.5 1.5 0 0 1 1.5 13V3A1.5 1.5 0 0 1 3 1.5h8a.5.5 0 0 1 0 1H3a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h10a.5.5 0 0 0 .5-.5V8a.5.5 0 0 1 1 0v5a1.5 1.5 0 0 1-1.5 1.5H3z"/>
                                <path d="m8.354 10.354 7-7a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z"/>
                            </svg>
                            <h5 style="line-height: 40px;" class="text-success">
                                خرید شما با موفقیت انجام شد و بلیط شما به ایمیل شما ارسال خواهد شد.
                            </h5>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a type="button" class="btn btn-secondary" data-bs-dismiss="modal">بستن</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

passangers/templates/passengers/payTest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body onload="document.forms['form'].submit()">
<form action="https://sep.shaparak.ir/MobilePG/MobilePayment" name="form" method="post">
    <input type="hidden" value="token" name="action">
    <input type="hidden" value="12594419" name="TerminalId">
    <input type="hidden" value="https://parsa.best" name="RedirectUrl">
    <input type="hidden" value="{{ info.ResNum }}" name="ResNum">
    <input type="hidden" value="{{ info.amount }}" name="Amount">
    <input type="hidden" value="{{ info.cell }}" name="CellNumber">
</form>
</body>
</html>