blog/urls.py
from django.urls import path

from .views import ArticleDetailView, ArticleListView, CategoryListView

app_name = "blog"
urlpatterns = [
    path("", ArticleListView.as_view(), name="list"),
    path("category/", CategoryListView.as_view(), name="category"),
    path("article/<int:id>/", ArticleListView.as_view(), name="detail"),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("airlines/", include("airlines.urls", namespace="airlines")),
    path("", include("passangers.urls", namespace="passengers")),
    path("hotels/", include("hotels.urls", namespace="hotel")),
    path("core/", include("core.urls", namespace="core")),
    path("job/", include("jobs.urls", namespace="job")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("pro/", include("profiles.urls", namespace="user_pro")),
    # path('api_doc/',include_docs_urls(title='7BLUSKY')),

]

if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

profiles/urls.py
from django.urls import path

from .views import EditUserView, Test

app_name = "user_pro"

urlpatterns = [
    path("edite/", EditUserView.as_view(), name="edite"),
    path("test/", Test.as_view(), name="test"),
]

profiles/models.py
from django.conf import settings
from django.db import models
from django_extensions.db.models import TimeStampedModel

user = settings.AUTH_USER_MODEL


# Create your models here.
class Profile(TimeStampedModel):
    user = models.OneToOneField(
        user,
        on_delete=models.CASCADE,
        related_name="profile",
        blank=True,
        null=True,
        verbose_name="کاربر",
    )
    first_name = models.CharField(
        max_length=125, verbose_name="نام ", blank=True, null=True
    )
    last_name = models.CharField(
        max_length=125, verbose_name="نام خانوادگی", blank=True, null=True
    )
    email = models.EmailField(verbose_name="ایمیل", blank=True, null=True)
    birthday = models.DateField(blank=True, null=True, verbose_name="تاریخ تولئ")

    def __str__(self):
        return f"{self.user} profile"

    class Meta:
        verbose_name = "پروفایل"
        verbose_name_plural = "پروفایل"


# from storages.backends.sftpstorage import SFTPStorage
#
# SFS = SFTPStorage()


def get_image_path(instance, filename):
    user = smart_str(instance.user.profile.first_name)
    directory = '/' + user
    if not os.path.exists(directory):
        os.makedirs(directory)
    full_path = str(directory) + "/%s" % (filename)
    return full_path


class Image_Doc(models.Model):
    file = models.ImageField(upload_to='')


class UserDocument(TimeStampedModel):
    TITLE = (
        ("شناسنامه", "شناسنامه"),
        ("کارت ملی", "کارت ملی"),
        ("پاسپورت", "پاسپورت"),
        ("سایر", "سایر"),
    )
    user = models.ForeignKey(
        user, on_delete=models.CASCADE, related_name="docs", blank=True, verbose_name=""
    )
    title = models.CharField(
        max_length=125, choices=TITLE, blank=True, verbose_name="عنوان"
    )
    image = models.OneToOneField(Image_Doc, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(blank=True, verbose_name="توضیحات")

    def __str__(self):
        return f"{self.user} docs"

    class Meta:
        verbose_name = "مدرک"
        verbose_name_plural = "مدارک"

profiles/forms.py
from django import forms

from .models import Profile, UserDocument


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            "first_name",
            "last_name",
            "email",
        )
        labels = {
            "first_name": "نام",
            "last_name": "نام خانوادگی",
            "email": "ایمیل",
        }
        widgets = {
            "first_name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "id": "travelSrc",
                    "placeholder": "نام",
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "id": "travelSrc",
                    "placeholder": "نام خانوادگی",
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "class": "form-control",
                    "id": "travelSrc",
                    "placeholder": "ایمیل",
                }
            ),
        }


class UserDocumentForm(forms.ModelForm):
    class Meta:
        model = UserDocument
        fields = ("title", "image", "description")
        widgets = {
            "image": forms.FileInput(
                attrs={
                    "class": "form-control",
                    "id": "travelSrc",
                    "placeholder": "",
                }
            ),
            "description": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "id": "travelSrc",
                    "placeholder": "",
                }
            ),
        }

profiles/views.py
# Import the logging module
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
# Import HttpResponse to send data to the browser
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView, TemplateView, View

from .forms import UserDocumentForm, UserProfileForm
from .models import Profile, UserDocument

# Define the logging configurations
logging.config.dictConfig({
    # Define the logging version
    'version': 1,
    # Enable the existing loggers
    'disable_existing_loggers': False,

    # Define the formatters
    'formatters': {
        'console': {
            'format': '%(message)s'
        },
        'file': {
            'format': '%(message)s'
        },

        # Define the handlers
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'console'
            },
            'file': {
                'level': 'DEBUG',
                'class': 'logging.FileHandler',
                'formatter': 'file',
                'filename': 'djangoapp.log'
            }
        },

        # Define the loggers
        'loggers': {
            'django': {
                'level': 'DEBUG',
                'handlers': ['file', 'console'],

            }
        }
    }

})

# Create the loggers object
logger = logging.getLogger('__name__')


# Create your views here.
class EditUserView(LoginRequiredMixin, View):
    form_class = UserProfileForm

    def get(self, request):
        form = self.form_class(instance=request.user.profile)
        return render(request, "profiles/edite.html", {"form": form})

    def post(self, request):
        form = self.form_class(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, "profile edited successfully", "success")
        return redirect("accounts:dashboard")


# class Test(View):
#     form_class = UserDocumentForm
#     template_name = "profiles/upload.html"
#
#     def get(self, request):
#         logger.error("Testing Django log...")
#         return render(request, self.template_name, {"form": self.form_class})
#
#     def post(self, request):
#         logger.error("Testing Django log...")
#         form = self.form_class(request.POST)
#         if form.is_valid():
#             user_doc = form.save(commit=False)
#             user_doc.user = self.request.user
#             user_doc.save()
#             messages.success(request, "", "success")
#         return redirect("accounts:dashboard")
from .models import Image_Doc


def handle_uploaded_file(f):
    destination = open('/tmp/upload/%s' % f.name, 'wb+')
    for chunk in f.chunks():
        destination.write(chunk)
    destination.close()


from django.contrib.auth import get_user_model

user_obj = get_user_model()


class Test(LoginRequiredMixin, View):
    def get(self, request):
        user_document = UserDocument.objects.filter(user=self.request.user)
        logger.error("Testing Django log...by elyas")
        return render(request, 'profiles/upload.html', {'object_list': user_document})

    def post(self, request):
        user = user_obj.objects.first()
        my_list = []
        for image in request.FILES.getlist('images'):
            Image_Doc.objects.create(file=image)
        user_docs = []
        for key, value in dict(request.POST).items():
            for i in range(0, len(value)):
                if len(user_docs) > i:
                    user_doc = user_docs[i]
                else:
                    user_doc = UserDocument()
                    user_doc.user = user
                if key == "madrak":
                    user_doc.title = value[i]
                if key == "description":
                    user_doc.description = value[i]
                    # user_doc.image = my_list[i]
                    # user.save()
                if len(user_docs) > i:
                    user_docs[i] = user_doc
                else:
                    user_docs.append(user_doc)

        UserDocument.objects.bulk_create(user_docs)

        # if len(user_docs) > i:
        #     user_docs[i] = user_docs
        # else:
        #     user_docs.append(user_doc)

        return redirect("accounts:dashboard")

profiles/templates/profiles/edite.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static "css/otherstyle.css" %}">
<link rel="stylesheet" href="{% static "css/common.css" %}">
<link rel="stylesheet" href="{% static "css/bootstrap.rtl.min.css" %}">
<link rel="stylesheet" href="{% static "css/animate.css" %}">
<link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
<title>تعویض رمز عبور</title>
{% endblock style %}

{% block content %}
<main>
    <h4 class="my-5">به روز رسانی پروفایل</h4>
    <section class="sign-in py-5">
        <div>
            <div class="sign-in-section d-flex flex-column align-items-center justify-content-CENTER px-5">
                <form class="w-100" method="post" action="">
                    {% csrf_token %}
                    <div class="input-group inputGP rounded-3 mx-2 my-3">
                  <span class="input-group-text inputGPText text-secondary"><svg xmlns="http://www.w3.org/2000/svg"
                                                                                 width="16" height="16"
                                                                                 fill="currentColor"
                                                                                 style="color: #A281B0;"
                                                                                 class="bi bi-people-fill me-1"
                                                                                 viewBox="0 0 16 16">
                    <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    <path fill-rule="evenodd"
                          d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
                    <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
                  </svg>
                     {{ form.first_name.label }}
                  </span>
                        {{ form.first_name }}
                    </div>
                    <div class="input-group inputGP rounded-3 mx-2 my-3">
                  <span class="input-group-text inputGPText text-secondary"><svg xmlns="http://www.w3.org/2000/svg"
                                                                                 width="16" height="16"
                                                                                 fill="currentColor"
                                                                                 style="color: #A281B0;"
                                                                                 class="bi bi-people-fill me-1"
                                                                                 viewBox="0 0 16 16">
                    <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    <path fill-rule="evenodd"
                          d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
                    <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
                  </svg>
                     {{ form.last_name.label }}
                  </span>
                        {{ form.last_name }}
                    </div>
                    <div class="input-group inputGP rounded-3 mx-2 my-3">
                  <span class="input-group-text inputGPText text-secondary"><svg xmlns="http://www.w3.org/2000/svg"
                                                                                 width="16" height="16"
                                                                                 fill="currentColor"
                                                                                 style="color: #A281B0;"
                                                                                 class="bi bi-people-fill me-1"
                                                                                 viewBox="0 0 16 16">
                    <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    <path fill-rule="evenodd"
                          d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
                    <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
                  </svg>
                     {{ form.email.label }}
                  </span>
                        {{ form.email }}
                    </div>


                    <div class="btnGP mt-5 d-flex flex-column justify-content-center align-items-center">
                        <div class="my-1 d-flex justify-content-center align-items-center">
                            <button type="submit" class="btn p-2 rounded-3 mx-1"
                                    style="background-color: #852193; color: white;">به روزسانی پروفایل<img
                                    src="{% static 'icons/chevron-left.svg' %}" height="16" width="16" alt=""></button>

                        </div>

                    </div>
                </form>
            </div>
        </div>
    </section>

    <section class="features px-5 py-5 my-5">
        <div class="icon-features d-flex flex-column align-items-center justify-content-end px-5"
             style="border-left: 1px dotted #A281B0;">
            <div class="d-flex double-feature mb-4">
                <div class="single-feature d-flex justify-content-center align-items-center flex-column mx-2">
                    <img class="my-2" src="{% static 'icons/icon2.png' %}" alt="icon">
                    <small class="my-1">پوشش ۱۰۰ درصدی پروازها</small>
                    <p class="my-1">خرید بلیط پروازهای داخلی و خارجی</p>
                </div>
                <div class="single-feature d-flex justify-content-center align-items-center flex-column mx-2">
                    <img class="my-2" src="{% static 'icons/icon1.png' %}" alt="icon">
                    <small class="my-1">دسترسی آسان از طریق وبسایت و موبایل</small>
                    <p class="my-1">ساده‌ترین و سریع‌ترین راه برای جستجو، خرید و استرداد بلیط</p>
                </div>
            </div>
            <div class="expand-feature rounded-3 w-100 mt-4 d-flex justify-content-center align-items-center flex-column">
                <img class="my-2" src="{% static 'icons/icon3.png' %}" alt="icon">
                <small class="my-1">تضمین بهترین خدمات برای مسافرین</small>
                <p class="my-1">معتبرترین و به‌صرفه‌ترین سامانه فروش بلیط با پشتیبانی ۲۴ ساعته</p>
            </div>
        </div>

        <div class="px-5 worldmap-feature d-flex justify-content-end align-items-center flex-column">
            <img src="{% static 'images/worldmap.png' %}" alt="icon">
            <p style="line-height: 30px;" class="mt-4 mb-0">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت
                چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم
                است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد</p>
        </div>
    </section>

</main>

{% endblock content %}

profiles/templates/profiles/upload.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static "css/passengers.css" %}">
<link rel="stylesheet" href="{% static "css/common.css" %}">
<link rel="stylesheet" href="{% static "css/bootstrap.rtl.min.css" %}">
<link rel="stylesheet" href="{% static "css/animate.css" %}">
<link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
<link rel="stylesheet" href="{% static "css/persian-datepicker.min.css" %}">
<title>تعویض رمز عبور</title>
{% endblock style %}

{% block content %}


<style>
    table.GeneratedTable {
        width: 100%;
        background-color: #ffffff;
        border-collapse: collapse;
        border-width: 2px;
        border-color: #c2c2c2;
        border-style: solid;
        color: #000000;
    }

    table.GeneratedTable td, table.GeneratedTable th {
        border-width: 2px;
        border-color: #c2c2c2;
        border-style: solid;
        padding: 3px;
    }

    table.GeneratedTable thead {
        background-color: #852193;
    }
</style>


<main>



    <h4 class="my-5"></h4>
    <section class="sign-in py-5">
            <section class="information mb-3 p-4 col-12">
        <div class="d-flex align-items-start">
            <svg class="bi bi-people-fill" fill="currentColor" height="30" viewBox="0 0 16 16"
                 width="30" xmlns="http://www.w3.org/2000/svg">
                <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                <path d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"
                      fill-rule="evenodd"/>
                <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
            </svg>
            <h4 class="ms-2 mt-1 fw-bold">مشخصات مسافران</h4>
        </div>
            <form id="file" method="post" enctype="multipart/form-data">
        <div class="file_wrapper">

                  <select aria-label="Default select example" class="form-select mx-2" name="madrak[]"  id="madrak">
                        <option selected>نوع مدرک</option>
                        <option value="کارت ملی">کارت ملی</option>
                        <option value="شناسنامه">شناسنامه</option>
                        <option value="پاسپورت">پاسپورت</option>
                        <option value="سایر مدارک">سایر مدارک</option>
                    </select>
                <div class="d-flex w-100 justify-content-between align-items-center">
                    <div class="input-group birth-date rounded-3 w-50 ms-2">
                    <input class="form-control" name="description[]" placeholder="توضیحات" type="text" id="description">
                   <div class="d-flex w-100 justify-content-between align-items-center">
                    <input class="form-control w-100" name="images" placeholder="مدرک" type="file">
                </div>
                </div>
                </div>

            </form>
            <hr>
        </div>
        <button class="btn btn-outline-primary" id="addNewfile" type="button">افزودن مدرک جدید</button>
    </section>


    </section>

    <section class="rules-submit mb-3 col-12 p-4 d-flex justify-content-between align-items-center">
        <div></div>
        <div class="d-flex justify-content-center align-items-end">
            <div class="text-primary me-2 d-flex align-items-center">
            </div>
            {%csrf_token%}
            <button data-url="{% url 'user_pro:test' %}" id="finalSubmit1" class="btn ms-2 fw-bold btn-primary">
                ارسال مدارک
            </button>
        </div>
    </section>










    <section class="features px-5 py-5 my-5">
        <div class="icon-features d-flex flex-column align-items-center justify-content-end px-5"
             style="border-left: 1px dotted #A281B0;">
            <div class="d-flex double-feature mb-4">
                <div class="single-feature d-flex justify-content-center align-items-center flex-column mx-2">
                    <img class="my-2" src="{% static 'icons/icon2.png' %}" alt="icon">
                    <small class="my-1">پوشش ۱۰۰ درصدی پروازها</small>
                    <p class="my-1">خرید بلیط پروازهای داخلی و خارجی</p>
                </div>
                <div class="single-feature d-flex justify-content-center align-items-center flex-column mx-2">
                    <img class="my-2" src="{% static 'icons/icon1.png' %}" alt="icon">
                    <small class="my-1">دسترسی آسان از طریق وبسایت و موبایل</small>
                    <p class="my-1">ساده‌ترین و سریع‌ترین راه برای جستجو، خرید و استرداد بلیط</p>
                </div>
            </div>
            <div class="expand-feature rounded-3 w-100 mt-4 d-flex justify-content-center align-items-center flex-column">
                <img class="my-2" src="{% static 'icons/icon3.png' %}" alt="icon">
                <small class="my-1">تضمین بهترین خدمات برای مسافرین</small>
                <p class="my-1">معتبرترین و به‌صرفه‌ترین سامانه فروش بلیط با پشتیبانی ۲۴ ساعته</p>
            </div>
        </div>

        <div class="px-5 worldmap-feature d-flex justify-content-end align-items-center flex-column">
            <img src="{% static 'images/worldmap.png' %}" alt="icon">
            <p style="line-height: 30px;" class="mt-4 mb-0">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت
                چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم
                است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد</p>
        </div>
    </section>

</main>

{% endblock content %}