accounts/api/urls.py
from django.urls import path

from .views import (LoginApiView, Logout, PasswordChangeApiView,
                    RegisterUserApiView, RegisterVerifyApiView,
                    UserUpdateApiView)

app_name='api'
urlpatterns = [
    path("login/", LoginApiView.as_view(), name="api_login"),
    path("password_change/",PasswordChangeApiView.as_view(),name='api_password_change'),
    path('logout/',Logout.as_view(),name='api_logout'),
    path('register/',RegisterUserApiView.as_view(),name='api_register'),
    path('verify/',RegisterVerifyApiView.as_view(),name='api_verify'),
    path('update/',UserUpdateApiView.as_view(),name='api_update'),
    # path("login/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]

accounts/urls.py
from django.urls import include, path

from accounts.api.urls import urlpatterns

from .views import (UserDashboard, UserLoginView, UserLogoutView,
                    UserPassChangeView, UserRegisterVerifyCodeView,
                    UserRegisterView, UserUpdateView)

app_name = "accounts"
urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("verify/", UserRegisterVerifyCodeView.as_view(), name="verify"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("profile/", UserDashboard.as_view(), name="dashboard"),
    path("pass_change/", UserPassChangeView.as_view(), name="pass_change"),
    path("update/<int:pk>/", UserUpdateView.as_view(), name="update"),
    path('api/', include(urlpatterns)),
]

blog/urls.py
from django.urls import path

from .views import ArticleDetailView, ArticleListView, CategoryListView

app_name = "blog"
urlpatterns = [
    path("", ArticleListView.as_view(), name="list"),
    path("category/", CategoryListView.as_view(), name="category"),
    path("article/<int:id>/", ArticleListView.as_view(), name="detail"),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("airlines/", include("airlines.urls", namespace="airlines")),
    path("", include("passangers.urls", namespace="passengers")),
    path("hotels/", include("hotels.urls", namespace="hotel")),
    path("core/", include("core.urls", namespace="core")),
    path("job/", include("jobs.urls", namespace="job")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("pro/", include("profiles.urls", namespace="user_pro")),
    # path('api_doc/',include_docs_urls(title='7BLUSKY')),

]

if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.validators import RegexValidator
from django.db import models
from django_extensions.db.models import TimeStampedModel

from .managers import MyUserManager
from .uitils import get_file_path


# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    phone_number = models.CharField(
        max_length=11,
        unique=True,
        verbose_name="شماره تلفن",
    )

    is_active = models.BooleanField(default=True, verbose_name="فعال")
    is_admin = models.BooleanField(default=False, verbose_name="ادمین")

    USERNAME_FIELD = "phone_number"
    REQUIRED_FIELDS = []

    objects = MyUserManager()

    # def __str__(self):
    # return self.phone_number

    @property
    def is_staff(self):
        return True

    class Meta:
        verbose_name = "کاربر"
        verbose_name_plural = "کاربران"


class OtpCode(models.Model):
    phone_number = models.CharField(max_length=11, verbose_name="شماره تماس")
    code = models.PositiveSmallIntegerField(verbose_name="کد ارسالی")
    created = models.DateTimeField(auto_now=True, verbose_name="تاریخ ارسال")

    def __str__(self):
        return f"{self.phone_number} - {self.code} - {self.created}"

    class Meta:
        verbose_name = "کد  ارسالی"
        verbose_name_plural = "کد های ارسالی"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import (PasswordChangeForm,
                                       ReadOnlyPasswordHashField)
from django.core.validators import ValidationError

from .models import User


class PassChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(PassChangeForm, self).__init__(*args, **kwargs)
        self.fields["old_password"].label = "رمز عبور فعلی"
        self.fields["new_password1"].label = "رمز عبور جدید "
        self.fields["new_password2"].label = "تکرار رمز عبور جدید"

        for fieldname in ["new_password1", "new_password2", "old_password"]:
            self.fields[fieldname].help_text = None
            # self.fields[fieldname].widget(forms.PasswordInput(attrs={'class': 'form-control'}))
            self.fields[fieldname].widget.attrs["class"] = "form-control"


class CreationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("phone_number",)

    def clean(self):
        clean_data = super(CreationForm, self).clean()
        password = clean_data.get("password")
        password_confirm = clean_data.get("password_confirm")
        if (password and password_confirm) and (password != password_confirm):
            raise ValidationError("un match password")
        return password

    def save(self, commit=True):
        user = super(CreationForm, self).save()
        user.set_password(self.changed_data["password"])
        if commit:
            user.save()
        return user


class ChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = (
            "phone_number",
            "password",
        )


class RegisterForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "travelSrc",
                "placeholder": "کلمه عبور",
            }
        )
    )
    password_confirm = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "travelSrc",
                "placeholder": "تکرار کلمه عبور",
            }
        )
    )

    class Meta:
        model = User
        fields = ("phone_number",)
        widgets = {
            "phone_number": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "id": "travelSrc",
                    "placeholder": "شماره تلفن",
                }
            ),
        }

    # def clean(self):
    #     clean_data = super(RegisterForm, self).clean()
    #     password = clean_data["password"]
    #     password_confirm = clean_data["password_confirm"]
    #     if (password and password_confirm) and (password != password_confirm):
    #         raise ValidationError("un match password")
    #     return password


class LoginForm(forms.Form):
    phone_number = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "id": "travelSrc", "placeholder": ""}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "id": "travelSrc", "placeholder": ""}
        )
    )


# class Meta:
#     model = User
#     fields = ("user_name", "password")
#     widgets = {
#         "user_name": forms.TextInput(
#             attrs={"class": "form-control", "id": "travelSrc", "placeholder": ""}
#         ),
#         "password": forms.PasswordInput(
#             attrs={"class": "form-control", "id": "travelSrc", "placeholder": ""}
#         ),
#     }


class VerifyCodeForm(forms.Form):
    code = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={"class": "form-control", "id": "travelSrc", "placeholder": ""}
        )
    )


class UserUpdateForm(RegisterForm):
    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields.pop("password")
        self.fields.pop("password_confirm")

accounts/api/views.py
from django.contrib.auth import authenticate
from rest_framework import status, serializers, generics
from rest_framework.authtoken.models import Token
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from django.contrib.auth import get_user_model
from .serializers import LoginSerializer, PasswordChangeSerializer, UserUpdateSerializer,RegisterUserSerializer,\
    RegisterVerifiedSerializer,PasswordResetSerializer,PasswordResetVerifiedSerializer
from django.contrib.auth import authenticate
import random
from accounts.models import OtpCode
from accounts.uitils import send_otp

User = get_user_model()


class LoginApiView(APIView):
    permission_classes = [AllowAny, ]
    serializer_class = LoginSerializer

    def post(self, request, format=None):
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            phone_number = serializer.data['phone_number']
            password = serializer.data['password']
            user = authenticate(request, phone_number=phone_number, password=password)
            if user:
                token, created = Token.objects.get_or_create(user=user)
                return Response({
                    'token': token.key,
                    'first_name': user.profile.first_name,
                    'last_name': user.profile.last_name,
                    'email': user.profile.email,
                    'birthday': user.profile.birthday,
                }, status=status.HTTP_200_OK)
            else:
                content = {'detail': 'Unable to login with provided credentials.'}
                return Response(content, status=status.HTTP_401_UNAUTHORIZED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class Logout(APIView):
    def get(self, request, format=None):
        # simply delete the token to force a login
        request.user.auth_token.delete()
        return Response(status=status.HTTP_200_OK)


# class Logout(APIView):
#     permission_classes = [IsAuthenticated, ]
#
#     def get(self, request, format=None):
#         """
#         Remove all auth tokens owned by request.user.
#         """
#         tokens = Token.objects.filter(user=request.user)
#         for token in tokens:
#             token.delete()
#         content = {'success': 'User logged out.'}
#         return Response(content, status=status.HTTP_200_OK)


class PasswordChangeApiView(generics.GenericAPIView):
    permission_classes = [IsAuthenticated, ]
    serializer_class = PasswordChangeSerializer

    def post(self, request):
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            new_password = serializer.data['new_password']
            old_password = serializer.data['old_password']

            if request.user.check_password(old_password):
                request.user.set_password(new_password)
                request.user.save()
                return Response(serializer.data, status=status.HTTP_200_OK)

            content = {'detail': 'your old password is not valid'}
            return Response(content, status=status.HTTP_400_BAD_REQUEST)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserUpdateApiView(generics.GenericAPIView):
    permission_classes = [IsAuthenticated, ]
    serializer_class = UserUpdateSerializer

    def get(self, request):
        serializer = self.serializer_class(request.user.profile)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def put(self, request):
        serializer = self.serializer_class(data=request.data, instance=request.user.profile, partial=True)
        if serializer.is_valid():
            serializer.save()
            content = {'success': 'update account.'}
            return Response(content, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class RegisterUserApiView(generics.GenericAPIView):
    permission_classes = [AllowAny, ]
    serializer_class = RegisterUserSerializer

    def post(self, request, format=None):
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            phone_number = serializer.data.get('phone_number')
            password = serializer.data.get('password')
            user = None
            try:
                user_exists = User.objects.get(phone_number=phone_number)
                if user_exists.is_active:
                    content = {'error': 'Duplicate user.'}
                    return Response(content, status=status.HTTP_400_BAD_REQUEST)
                else:
                    user = user_exists
            except:
                random_code = random.randint(1000, 9999)
                send_otp(phone_number, random_code)
                OtpCode.objects.create(phone_number=phone_number, code=random_code)
            content = {'success': 'otp code send.','phone_number':phone_number,'password':password,'code':random_code}
            return Response(content, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class RegisterVerifyApiView(generics.GenericAPIView):
    permission_classes = [AllowAny, ]
    serializer_class = RegisterVerifiedSerializer

    def post(self, request):
        serilizer = self.serializer_class(data=request.data)
        if serilizer.is_valid():
            phone_number = serilizer.data.get('phone_number')
            password = serilizer.data.get('password')
            code=serilizer.data.get('code')
            user_otp = OtpCode.objects.filter(phone_number=phone_number).last()
            if str(code) == str(user_otp.code):
                user=User.objects.create_user(phone_number=phone_number,password=password)
                user_otp.delete()
                token= Token.objects.create(user=user)
                content = {'success': 'user created',"token":token.key}
                return Response(content, status=status.HTTP_201_CREATED)

        return Response(serilizer.errors, status=status.HTTP_400_BAD_REQUEST)


class PasswordReset(generics.GenericAPIView):
    permission_classes = [AllowAny, ]
    serializer_class = PasswordResetSerializer

    def post(self, request):
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            phone_number = serializer.data['phone_number']

            try:
                user = User.objects.get(phone_number=phone_number)
                random_code = random.randint(1000, 9999)
                send_otp(phone_number, random_code)
                OtpCode.objects.create(phone_number=phone_number, code=random_code)
                content = {'success': 'code sent.'}
                return Response(content, status=status.HTTP_200_OK)

            except User.DoesNotExist:
                content = {'error': 'phone_number dose not exists..'}
                return Response(content, status=status.HTTP_400_BAD_REQUEST)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)




class PasswordResetVerify(generics.GenericAPIView):
    permission_classes = [AllowAny, ]
    serializer_class = PasswordResetVerifiedSerializer

    def post(self, request):
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            code = serializer.data['code']
            phone_number = serializer.data['phone_number']
            new_password = serializer.data['new_password']
            code_obj = OtpCode.objects.get(phone_number=phone_number,code=code)
            user_obj=User.objects.get(phone_number=phone_number)
            if code_obj :
                user_obj.set_password(new_password)
                user_obj.save()
                content = {'success': 'verify password.'}
                return Response(content, status=status.HTTP_200_OK)
            else:
                content={'error':'code is not match'}
                return Response(content, status=status.HTTP_400_BAD_REQUEST)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



accounts/templates/accounts/verify.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static "css/otherstyle.css" %}">
    <link rel="stylesheet" href="{% static "css/common.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap.rtl.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <title>ورود | عضویت</title>
{% endblock style %}

{% block content %}

    <main>
        <h4 class="my-5">تایید کد ارسالی</h4>
        <section class="sign-in py-5">
            <div>
                <div class="sign-in-section d-flex flex-column align-items-center justify-content-CENTER px-5">
                    <form method="post" action="{% url "accounts:verify" %}" class="w-100">
                        {% csrf_token %}
                        <div class="input-group inputGP rounded-3 mx-2 my-3">
                  <span class="input-group-text inputGPText text-secondary"><svg xmlns="http://www.w3.org/2000/svg"
                                                                                 width="16" height="16"
                                                                                 fill="currentColor"
                                                                                 style="color: #A281B0;"
                                                                                 class="bi bi-people-fill me-1"
                                                                                 viewBox="0 0 16 16">
                    <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    <path fill-rule="evenodd"
                          d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
                    <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
                  </svg>
                     کد ارسالی
                  </span>
                            {{ form.code }}
                        </div>

                        <div class="btnGP mt-5 d-flex flex-column justify-content-center align-items-center">
                            <div class="my-1 d-flex justify-content-center align-items-center">
                                <button type="submit" class="btn p-2 rounded-3 mx-1"
                                        style="background-color: #852193; color: white;">ورود به سیستم <img
                                        src="{% static 'icons/chevron-left.svg' %}" height="16" width="16" alt="">
                                </button>

                            </div>

                        </div>
                    </form>
                </div>
                <div class="px-5 signin-details d-flex justify-content-end align-items-start flex-column">
                    <p style="line-height: 30px; color: #A281B0;font-weight: bold;" class="mt-4 mb-0">شما با عضویت در وب
                        سایت علاوه بر پیوستن به خانواده ما و دسترسی به تمامی سرویس ها بصورت رایگان در بخش خدمات مشتریان
                        از امکانات زیر برخوردار خواهید شد</p>
                    <h4 style="color: #FFA809;" class="mt-4 mb-2">بخشی از امکانات باشگاه مشتریان</h4>
                    <ul class="d-flex ps-0 flex-wrap">
                        <li class="d-flex m-2">
                            <span class="me-2"><img src="{% static 'icons/check.svg' %}"
                                                    style="width: 25px; height: 25px;"
                                                    alt=""></span>
                            پشتیبانی آنلاین
                        </li>
                        <li class="d-flex m-2">
                            <span class="me-2"><img src="{% static 'icons/check.svg' %}"
                                                    style="width: 25px; height: 25px;"
                                                    alt=""></span>
                            خرید بلیط آنلاین
                        </li>
                        <li class="d-flex m-2">
                            <span class="me-2"><img src="{% static 'icons/check.svg' %}"
                                                    style="width: 25px; height: 25px;"
                                                    alt=""></span>
                            خدمات درخواست آنلاین
                        </li>
                        <li class="d-flex m-2">
                            <span class="me-2"><img src="{% static 'icons/check.svg' %}"
                                                    style="width: 25px; height: 25px;"
                                                    alt=""></span>
                            امکان استفاده از تخفیفات
                        </li>
                        <li class="d-flex m-2">
                            <span class="me-2"><img src="{% static 'icons/check.svg' %}"
                                                    style="width: 25px; height: 25px;"
                                                    alt=""></span>
                            ارسال پیشنهادات
                        </li>
                        <li class="d-flex m-2">
                            <span class="me-2"><img src="{% static 'icons/check.svg' %}"
                                                    style="width: 25px; height: 25px;"
                                                    alt=""></span>
                            استفاده از بلاگ
                        </li>
                        <li class="d-flex m-2">
                            <span class="me-2"><img src="{% static 'icons/check.svg' %}"
                                                    style="width: 25px; height: 25px;"
                                                    alt=""></span>
                            فرصت های شغلی
                        </li>
                        </ulclas>
                </div>
            </div>
        </section>

        <section class="features px-5 py-5 my-5">
            <div class="icon-features d-flex flex-column align-items-center justify-content-end px-5"
                 style="border-left: 1px dotted #A281B0;">
                <div class="d-flex double-feature mb-4">
                    <div class="single-feature d-flex justify-content-center align-items-center flex-column mx-2">
                        <img class="my-2" src="{% static 'icons/icon2.png' %}" alt="icon">
                        <small class="my-1">پوشش ۱۰۰ درصدی پروازها</small>
                        <p class="my-1">خرید بلیط پروازهای داخلی و خارجی</p>
                    </div>
                    <div class="single-feature d-flex justify-content-center align-items-center flex-column mx-2">
                        <img class="my-2" src="{% static 'icons/icon1.png' %}" alt="icon">
                        <small class="my-1">دسترسی آسان از طریق وبسایت و موبایل</small>
                        <p class="my-1">ساده‌ترین و سریع‌ترین راه برای جستجو، خرید و استرداد بلیط</p>
                    </div>
                </div>
                <div class="expand-feature rounded-3 w-100 mt-4 d-flex justify-content-center align-items-center flex-column">
                    <img class="my-2" src="{% static 'icons/icon3.png' %}" alt="icon">
                    <small class="my-1">تضمین بهترین خدمات برای مسافرین</small>
                    <p class="my-1">معتبرترین و به‌صرفه‌ترین سامانه فروش بلیط با پشتیبانی ۲۴ ساعته</p>
                </div>
            </div>

            <div class="px-5 worldmap-feature d-flex justify-content-end align-items-center flex-column">
                <img src="{% static 'images/worldmap.png' %}" alt="icon">
                <p style="line-height: 30px;" class="mt-4 mb-0">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت
                    چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم
                    است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد</p>
            </div>
        </section>

    </main>

{% endblock content %}