accounts/urls.py
from django.urls import include, path

from accounts.api.urls import urlpatterns

from .views import (UserDashboard, UserLoginView, UserLogoutView,
                    UserPassChangeView, UserRegisterVerifyCodeView,
                    UserRegisterView, UserUpdateView)

app_name = "accounts"
urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("verify/", UserRegisterVerifyCodeView.as_view(), name="verify"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("profile/", UserDashboard.as_view(), name="dashboard"),
    path("pass_change/", UserPassChangeView.as_view(), name="pass_change"),
    path("update/<int:pk>/", UserUpdateView.as_view(), name="update"),
    path('api/', include(urlpatterns)),
]

blog/urls.py
from django.urls import path

from .views import ArticleDetailView, ArticleListView, CategoryListView

app_name = "blog"
urlpatterns = [
    path("", ArticleListView.as_view(), name="list"),
    path("category/", CategoryListView.as_view(), name="category"),
    path("article/<int:id>/", ArticleListView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path

from .views import AboutUsView, ContactUsView, RulesView, WorkWithView

app_name = "core"
urlpatterns = [
    path("contact/", ContactUsView.as_view(), name="contact"),
    path("work/", WorkWithView.as_view(), name="work"),
    path("about_us/", AboutUsView.as_view(), name="about_us"),
    path("rules/", RulesView.as_view(), name="rules"),
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
# from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("airlines/", include("airlines.urls", namespace="airlines")),
    path("", include("passangers.urls", namespace="passengers")),
    path("hotels/", include("hotels.urls", namespace="hotel")),
    path("core/", include("core.urls", namespace="core")),
    path("job/", include("jobs.urls", namespace="job")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("pro/", include("profiles.urls", namespace="user_pro")),
    # path('api_doc/',include_docs_urls(title='7BLUSKY')),

]

if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

passangers/urls.py
from django.urls import path

from .views import (CancelTicketView, PassengerView, TripInfoView, cities,
                    go_to_gateway_view, home)

app_name = "passengers"
urlpatterns = [
    path("", home, name="home"),
    path(
        "cancel/ticket/<int:reserve_id>/",
        CancelTicketView.as_view(),
        name="cancel_reserve",
    ),
    path("trip/", TripInfoView.as_view(), name="trip"),
    # path("", go_to_gateway_view, name="pay"),
    path("toBank/", go_to_gateway_view, name="pay"),
    path("cities/", cities, name="cities"),
    path("passenger/", PassengerView.as_view(), name="passenger"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block style %}
    {% endblock style %}
    <title>صفحه اصلی | پرواز</title>
</head>
<body>

<style>

    window.scrollBy(0, 0);
    window.scrollBy(0, 400);

</style>

<header>
    <div class="head-address py-1">
        <div class="d-flex justify-content-start align-items-center flex-row-reverse">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="orange" class="bi bi-telephone-fill"
                 viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                      d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
            </svg>
            <p class="my-0 mx-3" dir="ltr">
                {{ setting.phone_number }}| {{ setting.address }}
            </p>
        </div>
    </div>
    <nav class="navbar py-0 navbar-expand-lg">
        <div class="container navContainer p-0">
            <button style="transform: translate(-8px, 10px);" class="navbar-toggler text-white p-0" type="button"
                    data-bs-toggle="collapse" data-bs-target="#mainNav" aria-controls="mainNav" aria-expanded="false"
                    aria-label="Toggle navigation">
                <div id="nav-icon">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="mobile-logo">
                <div class="nav-item rounded-3 d-flex align-items-center">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'accounts:dashboard' %}" type="button"
                       class="btn btn-outline-danger rounded-3 btnSign"
                       style="padding: 10px; border: 2px dotted;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-people" viewBox="0 0 16 16">
                            <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"/>
                        </svg>
{% if request.user.profile.first_name %}
                        {{ request.user.first_name }}-{{ request.user.last_name }}
                        {% else %}
                        {{ request.user }}
                        {% endif %}
                        <br>
                         <h6>ورود به پروفایل کاربری</h6>
                        <hr>

                    </a>
                    {% else %}
                    <a href="{% url "accounts:login" %}" type="button"
                       class="btn btn-outline-danger rounded-3 btnSign"
                       style="padding: 10px; border: 2px dotted;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-people" viewBox="0 0 16 16">
                        </svg>
                        عضویت | ورود کاربران
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="collapse navbar-collapse collapseNav" id="mainNav">
                <div class="navFields">
                    <a class="navbar-brand px-2" href="{% url 'passengers:home' %}">
                        <img width="50px" height="50px" src="{{ setting.logo.url }}">
                    </a>
                    <ul class="navbar-nav">
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url 'passengers:home' %}" role="button">
                                صفحه اصلی
                            </a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url 'passengers:home' %}" id="airNav" role="button" >
                                رزرو بلیط
                            </a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url 'passengers:home' %}" id="hotelNav" role="button">
                                رزرو هتل
                            </a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="" id="travelNav" role="button">
                                رزرو تور
                            </a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url 'core:about_us' %}" role="button">
                                درباره ما
                            </a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url 'core:contact' %}" role="button">
                                تماس با ما
                            </a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url 'blog:list' %}" role="button">
                                وبلاگ
                            </a>
                        </li>

                        <li class="nav-item mx-2">
                            <a class="nav-link" href="{% url 'job:category' %}" role="button">
                             فرصت های شغلی
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="nav-item rounded-3 d-flex align-items-center">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'accounts:dashboard' %}" type="button"
                       class="btn btn-outline-danger rounded-3 btnSign"
                       style="padding: 10px; border: 2px dotted;">
                      {% if request.user.profile.first_name %}
                        {{ request.user.first_name }}-{{ request.user.last_name }}
                        {% else %}
                        {{ request.user }}
                        {% endif %}



                    </a>
                    {% else %}
                    <a href="{% url 'accounts:login' %}" type="button"
                       class="btn btn-outline-danger rounded-3 btnSign"
                       style="padding: 10px; border: 2px dotted;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-people" viewBox="0 0 16 16">
                        </svg>
                        عضویت | ورود کاربران
                    </a>
                    {% endif %}

                </div>
            </div>
        </div>
    </nav>
    <div class="header-image-container">
        <section class="parallax-img"></section>
        <img class="plane-bottom" src="{% static 'images/abrB.png' %}" alt="">
        <span class="fog"></span>
    </div>
    <div class="header-image-mobile" style="display: none;">
        <section class="mobile-img"><img src="{% static 'images/airplane.jfif' %}" alt=""></section>
        <img class="mobile-plane-bottom" src="{% static 'images/abrB.png' %}" alt="">
        <span class="fog"></span>
    </div>
</header>
<div class="alert alert-success">

</div>
{% if messages %}
    {% for message in messages %}
    <p class="{{ message.tags }}">{{ message }}</p>
    {% endfor %}
{% endif %}

{% block content %}
{% endblock content %}
<footer>

    <div class="footer-content">
        <div class="social-media p-3 rounded-3 d-flex flex-column justify-content-evenly align-items-center">
            <div class="foot-logo">
                <img width="50px" height="50px" src="{{ setting.logo.url }}">
            </div>
            <div class="socialLinks flex-row">
                <a href="{{ setting.twitter }}" title="twitter"><img class="twitterLink"
                                                                     src="https://img.icons8.com/windows/32/ffffff/twitter.png"/></a>
                <a href="{{ setting.instagram }}" title="instagram"><img class="instaLink"
                                                                         src="https://img.icons8.com/windows/32/ffffff/instagram-new.png"/></a>
                <a href="{{ setting.facebook }}" title="facebook"><img class="facebookLink"
                                                                       src="https://img.icons8.com/windows/32/ffffff/facebook-new.png"/></a>
                <a href="{{ setting.linkedin }}" title="linkedin"><img class="linkedinLink"
                                                                       src="https://img.icons8.com/windows/32/ffffff/linkedin.png"/></a>
            </div>
        </div>
        <div class="footer-list rounded-3 p-4">
            <ul class="me-5 mb-0 ps-0">
                <li><a href="{% url 'accounts:login' %} ">ثبت نام در سایت</a></li>
                <li><a href="{% url 'hotel:list' %}">رزرو هتل</a></li>
                <li><a href="tourDetails.html">رزرو تور</a></li>
            </ul>
            <ul class="ms-5 mb-0">
                <li><a href="{% url 'core:about_us' %} ">درباره ما</a></li>
                <li><a href="{% url 'core:rules' %} ">قوانین و مقررات</a></li>
                <li><a href="{% url 'core:contact' %} ">تماس با ما</a></li>
            </ul>
        </div>
        <div class="e-namad">
            <a referrerpolicy="origin" target="_blank"
               href="https://trustseal.enamad.ir/?id=105429&amp;Code=fQ2m2hoJGLfuBArqXZoS"><img referrerpolicy="origin"
                                                                                                src="https://Trustseal.eNamad.ir/logo.aspx?id=105429&amp;Code=fQ2m2hoJGLfuBArqXZoS"
                                                                                                alt=""
                                                                                                style="cursor:pointer"
                                                                                                id="fQ2m2hoJGLfuBArqXZoS"></a>
        </div>
    </div>
    <div class="copyright">
        {{ setting.copyrights }} <a style="text-decoration: none;" href="https://crossapp.ir">
    </div>
    <div class="foot">
        <img src="" alt="">
    </div>
</footer>

<script src="{% static  'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static  'js/jquery.meanmenu.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/persian-date.min.js' %}"></script>
<script src="{% static 'js/persian-datepicker.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/upload.js' %}"></script>



</body>
</html>